myClass.lo: /Users/didi/PhpstormProjects/c/php-src/ext/myClass/myClass.c
	$(LIBTOOL) --mode=compile $(CC) -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/Users/didi/PhpstormProjects/c/php-src/ext/myClass $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/didi/PhpstormProjects/c/php-src/ext/myClass/myClass.c -o myClass.lo 
$(phplibdir)/myClass.la: ./myClass.la
	$(LIBTOOL) --mode=install cp ./myClass.la $(phplibdir)

./myClass.la: $(shared_objects_myClass) $(MYCLASS_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS)  -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_myClass) $(MYCLASS_SHARED_LIBADD)

